---
abstract: 'change shebang lines for relocatable perl'
author:
  - 'Shoichi Kaji <skaji@cpan.org>'
build_requires:
  Test::More: '0.98'
configure_requires:
  Module::Build: '0.38'
dynamic_config: 0
generated_by: 'Minilla/v2.1.1, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-ChangeShebang
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  App::ChangeShebang:
    file: lib/App/ChangeShebang.pm
    version: '0.03'
requires:
  perl: '5.008001'
resources:
  bugtracker: https://github.com/shoichikaji/change-shebang/issues
  homepage: https://github.com/shoichikaji/change-shebang
  repository: git://github.com/shoichikaji/change-shebang.git
version: '0.03'
x_authority: cpan:SKAJI
